#ifndef APP_RESOURCE_BUDGET_H
#define APP_RESOURCE_BUDGET_H

#include <stdint.h>

#define APP_RESOURCE_STACK_WORD_BYTES (4U)

#define APP_RESOURCE_PROTOCOL_STACK_WORDS (256U)
#define APP_RESOURCE_ACQUISITION_STACK_WORDS (256U)
#define APP_RESOURCE_CAN_STACK_WORDS (256U)
#define APP_RESOURCE_HEALTH_STACK_WORDS (256U)
#define APP_RESOURCE_DIAGNOSTIC_STACK_WORDS (256U)
#define APP_RESOURCE_IDLE_STACK_WORDS (128U)

#define APP_RESOURCE_DIAGNOSTIC_EVENT_QUEUE_DEPTH (8U)
#define APP_RESOURCE_DIAGNOSTIC_EVENT_ITEM_BYTES (12U)
#define APP_RESOURCE_DIAGNOSTIC_EVENT_STORAGE_BYTES                      \
  (APP_RESOURCE_DIAGNOSTIC_EVENT_QUEUE_DEPTH *                          \
   APP_RESOURCE_DIAGNOSTIC_EVENT_ITEM_BYTES)
#define APP_RESOURCE_DIAGNOSTIC_EVENT_DRAIN_BUDGET (2U)

#define APP_RESOURCE_CAN_IRQ_MAILBOX_BYTES (156U)
#define APP_RESOURCE_CAN_IRQ_NOTIFIER_BYTES (4U)
#define APP_RESOURCE_CAN_IRQ_STATIC_BYTES                              \
  (APP_RESOURCE_CAN_IRQ_MAILBOX_BYTES +                               \
   APP_RESOURCE_CAN_IRQ_NOTIFIER_BYTES)

#define APP_RESOURCE_CAN_TX_SCHEDULER_BYTES (324U)
#define APP_RESOURCE_CAN_CONTROLLER_BYTES (60U)
#define APP_RESOURCE_CAN_RUNTIME_SNAPSHOT_BYTES (140U)
#define APP_RESOURCE_CAN_DIAGNOSTIC_RESPONDER_BYTES (28U)
#define APP_RESOURCE_CAN_DIAGNOSTIC_REPORT_BYTES (112U)
#define APP_RESOURCE_CAN_RUNTIME_CONTROL_BYTES (12U)
#define APP_RESOURCE_CAN_RUNTIME_STATIC_BYTES                         \
  (APP_RESOURCE_CAN_TX_SCHEDULER_BYTES +                             \
   APP_RESOURCE_CAN_CONTROLLER_BYTES +                              \
   APP_RESOURCE_CAN_RUNTIME_SNAPSHOT_BYTES +                        \
   APP_RESOURCE_CAN_DIAGNOSTIC_RESPONDER_BYTES +                    \
   APP_RESOURCE_CAN_DIAGNOSTIC_REPORT_BYTES +                       \
   APP_RESOURCE_CAN_RUNTIME_CONTROL_BYTES)
#define APP_RESOURCE_CAN_STATIC_BYTES                                \
  (APP_RESOURCE_CAN_IRQ_STATIC_BYTES +                              \
   APP_RESOURCE_CAN_RUNTIME_STATIC_BYTES)

#define APP_RESOURCE_TASK_STACK_WORDS_TOTAL                               \
  (APP_RESOURCE_PROTOCOL_STACK_WORDS +                                   \
   APP_RESOURCE_ACQUISITION_STACK_WORDS + APP_RESOURCE_CAN_STACK_WORDS + \
   APP_RESOURCE_HEALTH_STACK_WORDS + APP_RESOURCE_DIAGNOSTIC_STACK_WORDS)

#define APP_RESOURCE_TASK_STACK_BYTES_TOTAL                              \
  (APP_RESOURCE_TASK_STACK_WORDS_TOTAL * APP_RESOURCE_STACK_WORD_BYTES)

#define APP_RESOURCE_MSP_STACK_BYTES (1024U)
#define APP_RESOURCE_LINKER_HEAP_BYTES (0U)
#define APP_RESOURCE_EXPLICIT_STACK_BYTES_TOTAL                       \
  (APP_RESOURCE_TASK_STACK_BYTES_TOTAL +                             \
   (APP_RESOURCE_IDLE_STACK_WORDS * APP_RESOURCE_STACK_WORD_BYTES) + \
   APP_RESOURCE_MSP_STACK_BYTES)

#define APP_RESOURCE_FLASH_LIMIT_BYTES (384U * 1024U)
#define APP_RESOURCE_STATIC_RAM_LIMIT_BYTES (96U * 1024U)

#endif
