#ifndef APP_RESOURCE_BUDGET_H
#define APP_RESOURCE_BUDGET_H

#include <stdint.h>

#define APP_RESOURCE_STACK_WORD_BYTES (4U)

#define APP_RESOURCE_PROTOCOL_STACK_WORDS (256U)
#define APP_RESOURCE_ACQUISITION_STACK_WORDS (256U)
#define APP_RESOURCE_CAN_STACK_WORDS (256U)
#define APP_RESOURCE_HEALTH_STACK_WORDS (256U)
#define APP_RESOURCE_DIAGNOSTIC_STACK_WORDS (256U)
#define APP_RESOURCE_IDLE_STACK_WORDS (128U)

#define APP_RESOURCE_DIAGNOSTIC_EVENT_QUEUE_DEPTH (8U)
#define APP_RESOURCE_DIAGNOSTIC_EVENT_ITEM_BYTES (12U)
#define APP_RESOURCE_DIAGNOSTIC_EVENT_STORAGE_BYTES                      \
  (APP_RESOURCE_DIAGNOSTIC_EVENT_QUEUE_DEPTH *                          \
   APP_RESOURCE_DIAGNOSTIC_EVENT_ITEM_BYTES)
#define APP_RESOURCE_DIAGNOSTIC_EVENT_DRAIN_BUDGET (2U)

#define APP_RESOURCE_TASK_STACK_WORDS_TOTAL                               \
  (APP_RESOURCE_PROTOCOL_STACK_WORDS +                                   \
   APP_RESOURCE_ACQUISITION_STACK_WORDS + APP_RESOURCE_CAN_STACK_WORDS + \
   APP_RESOURCE_HEALTH_STACK_WORDS + APP_RESOURCE_DIAGNOSTIC_STACK_WORDS)

#define APP_RESOURCE_TASK_STACK_BYTES_TOTAL                              \
  (APP_RESOURCE_TASK_STACK_WORDS_TOTAL * APP_RESOURCE_STACK_WORD_BYTES)

#define APP_RESOURCE_MSP_STACK_BYTES (1024U)
#define APP_RESOURCE_LINKER_HEAP_BYTES (0U)
#define APP_RESOURCE_EXPLICIT_STACK_BYTES_TOTAL                       \
  (APP_RESOURCE_TASK_STACK_BYTES_TOTAL +                             \
   (APP_RESOURCE_IDLE_STACK_WORDS * APP_RESOURCE_STACK_WORD_BYTES) + \
   APP_RESOURCE_MSP_STACK_BYTES)

#define APP_RESOURCE_FLASH_LIMIT_BYTES (384U * 1024U)
#define APP_RESOURCE_STATIC_RAM_LIMIT_BYTES (96U * 1024U)

#endif
